import type { Metadata } from "next";
import "./globals.css";
import { openSans, robotoSlab } from "@/lib/fonts";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${openSans.variable} ${robotoSlab.variable}`}>
        {children}
      </body>
    </html>
  );
}
